## Final Project Part - II

### In this part, we will be creating tables and loading data into the tables using the ERD in Part - I.


1. Identify the features (attributes) in Chicago Crime dataset and design an entity-relationship model
2. Refine the model and convert each relation to BCNF (if required)
3. Using DDL implement the relations in a Postgres server
4. Load the given data to the relations
5. Execute some interesting queries on the relations

## 2.1 Using DDL, create each of the relations in the postgres server.

In [151]:
import getpass
mypasswd = getpass.getpass()

········

In [119]:
# Then connects to the DB
from sqlalchemy.engine.url import URL
from sqlalchemy import create_engine
# -------------- Add Content Below
import psycopg2
import numpy as np
from psycopg2.extensions import adapt, register_adapter, AsIs
# SQLAlchemy Connection Parameters
connection = psycopg2.connect(database = 'dsa_student',
user = 'spnf4',
host = 'pgsql.dsa.lan',
password = mypasswd)

cursor = connection.cursor()

In [100]:
sqlCreateTable = """
CREATE TABLE IF NOT EXISTS spnf4.crime_code(
iucr VARCHAR(50) NOT NULL,
fbi_code VARCHAR(50) NOT NULL,
description VARCHAR(50),
primary_type VARCHAR(50),
PRIMARY KEY (iucr,fbi_code)
);"""
cursor.execute(sqlCreateTable)
connection.commit()

In [101]:
sqlCreateTable = """
CREATE TABLE IF NOT EXISTS spnf4.location_area(
la_id INT NOT NULL PRIMARY KEY,
beat INT,
district INT,
ward INT,
community_area INT
);"""
cursor.execute(sqlCreateTable)
connection.commit()

In [102]:
sqlCreateTable = """
CREATE TABLE IF NOT EXISTS spnf4.location_block(
lb_id INT NOT NULL PRIMARY KEY,
block VARCHAR(150)
);"""
cursor.execute(sqlCreateTable)
connection.commit()

In [103]:
sqlCreateTable = """
CREATE TABLE IF NOT EXISTS spnf4.location_description(
ld_id INT NOT NULL PRIMARY KEY,
location_description VARCHAR(50)
);"""
cursor.execute(sqlCreateTable)
connection.commit()

In [104]:
sqlCreateTable = """
CREATE TABLE IF NOT EXISTS spnf4.location_coordinate(
lc_id INT NOT NULL PRIMARY KEY,
x_coordinate INT,
y_coordinate INT,
latitude FLOAT,
longitude FLOAT,
location VARCHAR(50)
);"""
cursor.execute(sqlCreateTable)
connection.commit()

In [105]:
sqlCreateTable = """
CREATE TABLE IF NOT EXISTS spnf4.crime_location(
cl_id INT NOT NULL PRIMARY KEY,
la_id INT,
lb_id INT,
lc_id INT,
ld_id INT,
FOREIGN KEY (la_id)
    REFERENCES location_area(la_id),
FOREIGN KEY (lb_id)
    REFERENCES location_block(lb_id),
FOREIGN KEY (lc_id)
    REFERENCES location_coordinate(lc_id),
FOREIGN KEY (ld_id)
    REFERENCES location_description(ld_id)
);"""
cursor.execute(sqlCreateTable)
connection.commit()

In [ ]:
sqlCreateTable = """
CREATE TABLE IF NOT EXISTS spnf4.crime_record(
id INT NOT NULL PRIMARY KEY,
iucr VARCHAR(50),
fbi_code VARCHAR(50),
cl_id INT,
unnamed_id INT,
case_number VARCHAR(50),
arrest VARCHAR(10),
domestic VARCHAR(10),
crime_date TIMESTAMP,
year INT,
updated_on TIMESTAMP,
CONSTRAINT crime_code_pkey
FOREIGN KEY (iucr,fbi_code)
    REFERENCES crime_code(iucr,fbi_code),
FOREIGN KEY (cl_id)
    REFERENCES crime_location(cl_id)
);"""
cursor.execute(sqlCreateTable)
connection.commit()

## 2.2 Show the table's definition for each table using psql or querying the information_schema.colums catalog

* Add additional cells if required

\d crime_code
                       Table "spnf4.crime_code"
    Column    |         Type          | Collation | Nullable | Default
--------------+-----------------------+-----------+----------+---------
 iucr         | character varying(50) |           | not null |
 fbi_code     | character varying(50) |           | not null |
 description  | character varying(50) |           |          |
 primary_type | character varying(50) |           |          |
Indexes:
    "crime_code_pkey" PRIMARY KEY, btree (iucr, fbi_code)
Referenced by:
    TABLE "crime_record" CONSTRAINT "crime_code_pkey" FOREIGN KEY (iucr, fbi_code) REFERENCES crime_code(iucr, fbi_code)

\d location_area
                Table "spnf4.location_area"
     Column     |  Type   | Collation | Nullable | Default
----------------+---------+-----------+----------+---------
 la_id          | integer |           | not null |
 beat           | integer |           |          |
 district       | integer |           |          |
 ward           | integer |           |          |
 community_area | integer |           |          |
Indexes:
    "location_area_pkey" PRIMARY KEY, btree (la_id)
Referenced by:
    TABLE "crime_location" CONSTRAINT "crime_location_la_id_fkey" FOREIGN KEY (la_id) REFERENCES location_area(la_id)


dsa_student=> \d location_block
                   Table "spnf4.location_block"
 Column |          Type          | Collation | Nullable | Default
--------+------------------------+-----------+----------+---------
 lb_id  | integer                |           | not null |
 block  | character varying(150) |           |          |
Indexes:
    "location_block_pkey" PRIMARY KEY, btree (lb_id)
Referenced by:
    TABLE "crime_location" CONSTRAINT "crime_location_lb_id_fkey" FOREIGN KEY (lb_id) REFERENCES location_block(lb_id)


dsa_student=> \d location_coordinate
                   Table "spnf4.location_coordinate"
    Column    |         Type          | Collation | Nullable | Default
--------------+-----------------------+-----------+----------+---------
 lc_id        | integer               |           | not null |
 x_coordinate | integer               |           |          |
 y_coordinate | integer               |           |          |
 latitude     | double precision      |           |          |
 longitude    | double precision      |           |          |
 location     | character varying(50) |           |          |
Indexes:
    "location_coordinate_pkey" PRIMARY KEY, btree (lc_id)
Referenced by:
    TABLE "crime_location" CONSTRAINT "crime_location_lc_id_fkey" FOREIGN KEY (lc_id) REFERENCES location_coordinate(lc_id)


dsa_student=> \d location_description
                      Table "spnf4.location_description"
        Column        |         Type          | Collation | Nullable | Default
----------------------+-----------------------+-----------+----------+---------
 ld_id                | integer               |           | not null |
 location_description | character varying(50) |           |          |
Indexes:
    "location_description_pkey" PRIMARY KEY, btree (ld_id)
Referenced by:
    TABLE "crime_location" CONSTRAINT "crime_location_ld_id_fkey" FOREIGN KEY (ld_id) REFERENCES location_description(ld_id)

\d crime_location
           Table "spnf4.crime_location"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 cl_id  | integer |           | not null |
 la_id  | integer |           |          |
 lb_id  | integer |           |          |
 lc_id  | integer |           |          |
 ld_id  | integer |           |          |
Indexes:
    "crime_location_pkey" PRIMARY KEY, btree (cl_id)
Foreign-key constraints:
    "crime_location_la_id_fkey" FOREIGN KEY (la_id) REFERENCES location_area(la_id)
    "crime_location_lb_id_fkey" FOREIGN KEY (lb_id) REFERENCES location_block(lb_id)
    "crime_location_lc_id_fkey" FOREIGN KEY (lc_id) REFERENCES location_coordinate(lc_id)
    "crime_location_ld_id_fkey" FOREIGN KEY (ld_id) REFERENCES location_description(ld_id)
Referenced by:
    TABLE "crime_record" CONSTRAINT "crime_record_cl_id_fkey" FOREIGN KEY (cl_id) REFERENCES crime_location(cl_id)


dsa_student=> \d crime_record
                         Table "spnf4.crime_record"
   Column    |            Type             | Collation | Nullable | Default
-------------+-----------------------------+-----------+----------+---------
 id          | integer                     |           | not null |
 iucr        | character varying(50)       |           |          |
 fbi_code    | character varying(50)       |           |          |
 cl_id       | integer                     |           |          |
 unnamed_id  | integer                     |           |          |
 case_number | character varying(50)       |           |          |
 arrest      | character varying(10)       |           |          |
 domestic    | character varying(10)       |           |          |
 crime_date  | timestamp without time zone |           |          |
 year        | integer                     |           |          |
 updated_on  | timestamp without time zone |           |          |
Indexes:
    "crime_record_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "crime_code_pkey" FOREIGN KEY (iucr, fbi_code) REFERENCES crime_code(iucr, fbi_code)
    "crime_record_cl_id_fkey" FOREIGN KEY (cl_id) REFERENCES crime_location(cl_id)

## 2.3 Load the data from the csv file in Part 1 to the relations

In [52]:
import pandas as pd
import numpy as np

df = pd.read_csv("Chicago-Crime-Sample--2012.csv")
df.head()

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,47398,10433096,HZ170962,01-01-2012 00:00,026XX N MC VICKER AVE,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,RESIDENCE,True,...,29.0,19.0,17,1135617,1916918,2012,04-02-2016 06:33,41.928203,-87.777079,"(41.928202943, -87.777079437)"
1,47420,10433124,HZ170983,01-01-2012 00:00,026XX N MC VICKER AVE,1544,SEX OFFENSE,SEXUAL EXPLOITATION OF A CHILD,RESIDENCE,True,...,29.0,19.0,17,1135617,1916918,2012,04-02-2016 06:33,41.928203,-87.777079,"(41.928202943, -87.777079437)"
2,802910,10532867,HZ276514,01-01-2012 00:00,036XX S RHODES AVE,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,APARTMENT,False,...,4.0,35.0,17,1180179,1881011,2012,04-02-2016 06:33,41.828762,-87.614436,"(41.828762287, -87.614436164)"
3,803605,10536876,HZ280873,01-01-2012 00:00,062XX S ROCKWELL ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,...,15.0,66.0,11,1160111,1863230,2012,04-02-2016 06:33,41.780406,-87.639933,"(41.774357248, -87.639932837)"
4,831733,9581929,HX232501,01-01-2012 00:00,006XX W 66TH ST,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,False,...,6.0,68.0,17,1173390,1861129,2012,04-02-2016 06:33,41.774357,-87.639933,"(41.774357248, -87.639932837)"

In [74]:
df1 = df.copy()
df1.head()

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,47398,10433096,HZ170962,01-01-2012 00:00,026XX N MC VICKER AVE,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,RESIDENCE,True,...,29.0,19.0,17,1135617,1916918,2012,04-02-2016 06:33,41.928203,-87.777079,"(41.928202943, -87.777079437)"
1,47420,10433124,HZ170983,01-01-2012 00:00,026XX N MC VICKER AVE,1544,SEX OFFENSE,SEXUAL EXPLOITATION OF A CHILD,RESIDENCE,True,...,29.0,19.0,17,1135617,1916918,2012,04-02-2016 06:33,41.928203,-87.777079,"(41.928202943, -87.777079437)"
2,802910,10532867,HZ276514,01-01-2012 00:00,036XX S RHODES AVE,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,APARTMENT,False,...,4.0,35.0,17,1180179,1881011,2012,04-02-2016 06:33,41.828762,-87.614436,"(41.828762287, -87.614436164)"
3,803605,10536876,HZ280873,01-01-2012 00:00,062XX S ROCKWELL ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,RESIDENCE,False,...,15.0,66.0,11,1160111,1863230,2012,04-02-2016 06:33,41.780406,-87.639933,"(41.774357248, -87.639932837)"
4,831733,9581929,HX232501,01-01-2012 00:00,006XX W 66TH ST,1563,SEX OFFENSE,CRIMINAL SEXUAL ABUSE,RESIDENCE,False,...,6.0,68.0,17,1173390,1861129,2012,04-02-2016 06:33,41.774357,-87.639933,"(41.774357248, -87.639932837)"

In [75]:
df1['Ward'] = df1['Ward'].fillna(0)
df1['Community Area'] = df1['Community Area'].fillna(0)
df1 = df1.astype({"Ward":int,"Community Area":int})
df1 = df1.astype({"X Coordinate": int, "Y Coordinate": int})

In [76]:
block = pd.DataFrame(df1.iloc[:,4])
block.drop_duplicates(subset='Block',inplace=True)
block.insert(0,'lb_id',range(1,1+len(block)))

In [77]:
block.tail()

        lb_id                 Block
334257  28336     032XX S GILES AVE
334288  28337      007XX E 130TH ST
334631  28338     010XX N HOOKER ST
334654  28339     029XX W FARGO AVE
334701  28340  052XX S LECLAIRE AVE

In [78]:
location_description = pd.DataFrame(df1.iloc[:,8])
location_description.drop_duplicates(subset='Location Description',inplace=True)
location_description.insert(0,'ld_id',range(1,1+len(location_description)))

In [79]:
location_description.tail()

        ld_id                          Location Description
29462      94                               FOREST PRESERVE
51354      95  AIRPORT TERMINAL MEZZANINE - NON-SECURE AREA
75214      96                                  CREDIT UNION
82396      97                               BOAT/WATERCRAFT
111658     98                                     NEWSSTAND

In [80]:
location_area = pd.DataFrame(df1.iloc[:,[11,12,13,14]])
location_area.drop_duplicates(subset=['Beat','District','Ward','Community Area'],inplace=True)
location_area.insert(0,'la_id',range(1,1+len(location_area)))

In [81]:
location_area.tail()

        la_id  Beat  District  Ward  Community Area
327422   1018  1221        12    26              23
331437   1019   822         8    16              65
331468   1020  1222        12    27              28
331859   1021   825        31    15              66
332831   1022  1221        12    27              24

In [82]:
location_coordinates = pd.DataFrame(df1.iloc[:,[16,17,20,21,22]])
location_coordinates.drop_duplicates(subset=['X Coordinate','Y Coordinate','Latitude','Longitude','Location'],inplace=True)
location_coordinates.dropna(inplace=True)
location_coordinates.insert(0,'lc_id',range(1,1+len(location_coordinates)))

In [83]:
location_coordinates.tail()

,lc_id,X Coordinate,Y Coordinate,Latitude,Longitude,Location
334701,162282,1143245,1869532,41.798030,-87.750232,"(41.79803032, -87.750231573)"
334702,162283,1161592,1921231,41.939536,-87.681510,"(41.939536003, -87.681509746)"
334706,162284,1150342,1914710,41.921869,-87.723028,"(41.921869111, -87.723027572)"
334709,162285,1169209,1858007,41.765882,-87.655350,"(41.76588157, -87.655349847)"
334714,162286,1128745,1924002,41.947762,-87.802171,"(41.947761848, -87.802170774)"

In [84]:
df1 = pd.merge(df1, block, on="Block")

In [85]:
df1 = pd.merge(df1, location_description, on="Location Description")
df1 = pd.merge(df1, location_area, on=['Beat','District','Ward','Community Area'])
df1 = pd.merge(df1, location_coordinates, on=['X Coordinate','Y Coordinate','Latitude','Longitude','Location'])

In [86]:
crime_location = pd.DataFrame(df1.iloc[:,[-1,-2,-3,-4]])
crime_location.head()

   lc_id  la_id  ld_id  lb_id
0      1      1      1      1
1      1      1      1      1
2      1      1      1      1
3  83698      1      1      1
4  83698      1      1      1

In [88]:
crime_location.drop_duplicates(subset=['lc_id','la_id','ld_id','lb_id'],inplace=True)
crime_location.insert(0,'cl_id',range(1,1+len(crime_location)))
crime_location.tail()

         cl_id   lc_id  la_id  ld_id  lb_id
334710  243412  139771    713     58  27466
334711  243413  136769    713     63  27341
334712  243414  155469    713     85  28099
334713  243415    4733    716     62   4046
334714  243416   12202    793     62   6574

In [89]:
crime_location = crime_location[['cl_id','la_id','lb_id','lc_id','ld_id']]

In [90]:
crime_location.tail()

         cl_id  la_id  lb_id   lc_id  ld_id
334710  243412    713  27466  139771     58
334711  243413    713  27341  136769     63
334712  243414    713  28099  155469     85
334713  243415    716   4046    4733     62
334714  243416    793   6574   12202     62

In [91]:
df1 = pd.merge(df1, crime_location, on=['lc_id','la_id','ld_id','lb_id'])

In [92]:
df1.columns

Index(['Unnamed: 0', 'ID', 'Case Number', 'Date', 'Block', 'IUCR',
       'Primary Type', 'Description', 'Location Description', 'Arrest',
       'Domestic', 'Beat', 'District', 'Ward', 'Community Area', 'FBI Code',
       'X Coordinate', 'Y Coordinate', 'Year', 'Updated On', 'Latitude',
       'Longitude', 'Location', 'lb_id', 'ld_id', 'la_id', 'lc_id', 'cl_id'],
      dtype='object')

In [93]:
crime_code = pd.DataFrame(df1.iloc[:,[5,15,6,7]])
crime_code.tail()

        IUCR FBI Code        Primary Type              Description
334710   820        6               THEFT           $500 AND UNDER
334711   820        6               THEFT           $500 AND UNDER
334712  1121       10  DECEPTIVE PRACTICE  COUNTERFEITING DOCUMENT
334713   810        6               THEFT                OVER $500
334714   810        6               THEFT                OVER $500

In [140]:
crime_code.drop_duplicates(subset=['IUCR','FBI Code'],inplace=True)
crime_code.tail()

        IUCR FBI Code          Primary Type                     Description
310562  2019       18             NARCOTICS  MANU/DELIVER:HEROIN(BLACK TAR)
324200   142      01B              HOMICIDE               RECKLESS HOMICIDE
330048  2240       22  LIQUOR LAW VIOLATION          MINOR MISREPRESENT AGE
331018  4860       26         OTHER OFFENSE         BOARD PLANE WITH WEAPON
332826  1335       26     CRIMINAL TRESPASS                      TO AIRPORT

In [95]:
crime_record = pd.DataFrame(df1.iloc[:,[1,5,15,-1,0,2,9,10,3,18,19]])
crime_record.head()

,ID,IUCR,FBI Code,cl_id,Unnamed: 0,Case Number,Arrest,Domestic,Date,Year,Updated On
0,10433096,1562,17,1,47398,HZ170962,True,False,01-01-2012 00:00,2012,04-02-2016 06:33
1,10433124,1544,17,1,47420,HZ170983,True,False,01-01-2012 00:00,2012,04-02-2016 06:33
2,8539915,890,6,1,2481315,HV216276,False,False,23-03-2012 14:00,2012,04-02-2016 06:33
3,8638377,486,08B,2,2542746,HV312790,False,True,31-05-2012 20:35,2012,04-02-2016 06:33
4,8641074,560,08A,2,2544718,HV315993,False,True,02-06-2012 22:45,2012,04-02-2016 06:33

In [96]:
crime_record.rename(columns={"Unnamed: 0":"Unnamed_id"},inplace=True)

In [109]:
crime_record['Date'] = pd.to_datetime(crime_record['Date'])

In [111]:
crime_record['Updated On'] = pd.to_datetime(crime_record['Updated On'])

In [112]:
crime_record.head()

,ID,IUCR,FBI Code,cl_id,Unnamed_id,Case Number,Arrest,Domestic,Date,Year,Updated On
0,10433096,1562,17,1,47398,HZ170962,True,False,2012-01-01 00:00:00,2012,2016-04-02 06:33:00
1,10433124,1544,17,1,47420,HZ170983,True,False,2012-01-01 00:00:00,2012,2016-04-02 06:33:00
2,8539915,890,6,1,2481315,HV216276,False,False,2012-03-23 14:00:00,2012,2016-04-02 06:33:00
3,8638377,486,08B,2,2542746,HV312790,False,True,2012-05-31 20:35:00,2012,2016-04-02 06:33:00
4,8641074,560,08A,2,2544718,HV315993,False,True,2012-02-06 22:45:00,2012,2016-04-02 06:33:00

In [117]:
print(list(block))
s = ''
for i in list(block):
    s+= '%s,'
print(s)

['lb_id', 'Block']
%s,%s,

In [121]:
import numpy as np
register_adapter(np.int64,AsIs)
register_adapter(np.float64,AsIs)
music_info = block.where(pd.notnull(block), None)
INSERT_SQL = 'INSERT INTO spnf4.location_block'
INSERT_SQL += ' (lb_id,Block) VALUES'
INSERT_SQL += '(%s, %s)'
print(INSERT_SQL)
with connection, connection.cursor() as cursor:
    for row in block.itertuples(index = False, name = None):
        cursor.execute(INSERT_SQL, row)

INSERT INTO spnf4.location_block (lb_id,Block) VALUES(%s, %s)

In [122]:
print(list(location_area))
s = ''
for i in list(location_area):
    s+= '%s,'
print(s)

['la_id', 'Beat', 'District', 'Ward', 'Community Area']
%s,%s,%s,%s,%s,

In [124]:
import numpy as np
register_adapter(np.int64,AsIs)
register_adapter(np.float64,AsIs)
music_info = location_area.where(pd.notnull(location_area), None)
INSERT_SQL = 'INSERT INTO spnf4.location_area'
INSERT_SQL += ' (la_id, beat, district, ward, community_area) VALUES'
INSERT_SQL += '(%s,%s,%s,%s,%s)'
print(INSERT_SQL)
with connection, connection.cursor() as cursor:
    for row in location_area.itertuples(index = False, name = None):
        cursor.execute(INSERT_SQL, row)

INSERT INTO spnf4.location_area (la_id, beat, district, ward, community_area) VALUES(%s,%s,%s,%s,%s)

In [126]:
print(list(location_coordinates))
s = ''
for i in list(location_coordinates):
    s+= '%s,'
print(s)

['lc_id', 'X Coordinate', 'Y Coordinate', 'Latitude', 'Longitude', 'Location']
%s,%s,%s,%s,%s,%s,

In [129]:
import numpy as np
register_adapter(np.int64,AsIs)
register_adapter(np.float64,AsIs)
music_info = location_coordinates.where(pd.notnull(location_coordinates), None)
INSERT_SQL = 'INSERT INTO spnf4.location_coordinate'
INSERT_SQL += ' (lc_id, x_coordinate, y_coordinate, latitude, longitude, location) VALUES'
INSERT_SQL += '(%s,%s,%s,%s,%s,%s)'
print(INSERT_SQL)
with connection, connection.cursor() as cursor:
    for row in location_coordinates.itertuples(index = False, name = None):
        cursor.execute(INSERT_SQL, row)

INSERT INTO spnf4.location_coordinate (lc_id, x_coordinate, y_coordinate, latitude, longitude, location) VALUES(%s,%s,%s,%s,%s,%s)

In [130]:
print(list(location_description))
s = ''
for i in list(location_description):
    s+= '%s,'
print(s)

['ld_id', 'Location Description']
%s,%s,

In [134]:
import numpy as np
register_adapter(np.int64,AsIs)
register_adapter(np.float64,AsIs)
music_info = location_description.where(pd.notnull(location_description), None)
INSERT_SQL = 'INSERT INTO spnf4.location_description'
INSERT_SQL += ' (ld_id, location_description) VALUES'
INSERT_SQL += '(%s,%s)'
print(INSERT_SQL)
with connection, connection.cursor() as cursor:
    for row in location_description.itertuples(index = False, name = None):
        cursor.execute(INSERT_SQL, row)

INSERT INTO spnf4.location_description (ld_id, location_description) VALUES(%s,%s)

In [135]:
print(list(crime_location))
s = ''
for i in list(crime_location):
    s+= '%s,'
print(s)

['cl_id', 'la_id', 'lb_id', 'lc_id', 'ld_id']
%s,%s,%s,%s,%s,

In [136]:
import numpy as np
register_adapter(np.int64,AsIs)
register_adapter(np.float64,AsIs)
music_info = crime_location.where(pd.notnull(crime_location), None)
INSERT_SQL = 'INSERT INTO spnf4.crime_location'
INSERT_SQL += ' (cl_id, la_id, lb_id, lc_id, ld_id) VALUES'
INSERT_SQL += '(%s,%s,%s,%s,%s)'
print(INSERT_SQL)
with connection, connection.cursor() as cursor:
    for row in crime_location.itertuples(index = False, name = None):
        cursor.execute(INSERT_SQL, row)

INSERT INTO spnf4.crime_location (cl_id, la_id, lb_id, lc_id, ld_id) VALUES(%s,%s,%s,%s,%s)

In [137]:
print(list(crime_code))
s = ''
for i in list(crime_code):
    s+= '%s,'
print(s)

['IUCR', 'FBI Code', 'Primary Type', 'Description']
%s,%s,%s,%s,

In [ ]:
ALTER TABLE crime_code
ALTER COLUMN description VARCHAR(50) VARCHAR(150);

In [139]:
import numpy as np
register_adapter(np.int64,AsIs)
register_adapter(np.float64,AsIs)
music_info = crime_code.where(pd.notnull(crime_code), None)
INSERT_SQL = 'INSERT INTO spnf4.crime_code'
INSERT_SQL += ' (iucr, fbi_code, primary_type, description) VALUES'
INSERT_SQL += '(%s,%s,%s,%s)'
print(INSERT_SQL)
with connection, connection.cursor() as cursor:
    for row in crime_code.itertuples(index = False, name = None):
        cursor.execute(INSERT_SQL, row)

INSERT INTO spnf4.crime_code (iucr, fbi_code, primary_type, description) VALUES(%s,%s,%s,%s)

In [142]:
print(list(crime_record))
s = ''
for i in list(crime_record):
    s+= '%s,'
print(s)

['ID', 'IUCR', 'FBI Code', 'cl_id', 'Unnamed_id', 'Case Number', 'Arrest', 'Domestic', 'Date', 'Year', 'Updated On']
%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,

In [145]:
import numpy as np
register_adapter(np.int64,AsIs)
register_adapter(np.float64,AsIs)
music_info = crime_record.where(pd.notnull(crime_record), None)
INSERT_SQL = 'INSERT INTO spnf4.crime_record'
INSERT_SQL += ' (id, iucr, fbi_code, cl_id, unnamed_id, case_number, arrest, domestic, crime_date, year, updated_on) VALUES'
INSERT_SQL += '(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)'
print(INSERT_SQL)
with connection, connection.cursor() as cursor:
    for row in crime_record.itertuples(index = False, name = None):
        cursor.execute(INSERT_SQL, row)

INSERT INTO spnf4.crime_record (id, iucr, fbi_code, cl_id, unnamed_id, case_number, arrest, domestic, crime_date, year, updated_on) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)

## 2.4 For each table, show the table name and number of rows using a sql query

In [153]:
#masked all the three below for security reasons
SSO = '****'
hostname = '******' 
database = '******'

In [154]:
#Read password
import getpass
read_password = getpass.getpass("Type Password and hit enter")

Type Password and hit enter········

In [155]:
%load_ext sql
connection_string = "postgresql://{user}:{password}@{host}/{database}".format(user=SSO, password=read_password, host=hostname, database=database)
%sql $connection_string

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: spnf4@dsa_student'

## 2.5 Developed five distinct and useful queries that could be potentially used for policing planning, policy making, citizen awareness, etc.

* Queries provides some analytic values using GROUP BY/HAVING, Nested Queries, Aggregation Operators, etc.
* Each query has documentation to explain what this query is looking for and why it is meaningful for what purposes.

Top ten areas with most cases so that the residents of that particular community will be more cautious

In [160]:
%%sql
SELECT la.community_area ,COUNT(la.community_area) AS FREQUENCY
FROM crime_record cr 
JOIN crime_location cl ON cl.cl_id = cr.cl_id
JOIN location_area la ON cl.la_id = la.la_id
JOIN crime_code cc ON cc.iucr = cr.iucr AND cc.fbi_code = cr.fbi_code
GROUP BY la.community_area
ORDER BY COUNT(la.community_area) DESC
LIMIT 10

 * postgresql://spnf4:***@pgsql.dsa.lan/dsa_student
10 rows affected.

[(25, 21269),
 (43, 11573),
 (8, 11270),
 (23, 11167),
 (29, 10331),
 (67, 9948),
 (24, 9666),
 (71, 9386),
 (28, 9385),
 (68, 9059)]

Retail theft charges can generally be defined as a crime wherein an individual unlawfully takes possession of, carries away, or transfers any retail goods or merchandise offered for sale by a retail establishment. People should install silent alarms in the shops so that the cops would know about the burglury before the thieves leaves the shop.

In [167]:
%%sql
SELECT lb.block,cc.description, COUNT(*) FROM crime_code cc
JOIN crime_record cr ON cr.iucr = cc.iucr AND cr.fbi_code = cc.fbi_code
JOIN crime_location cl ON cl.cl_id = cr.cl_id
JOIN location_block lb ON lb.lb_id = cl.lb_id
GROUP BY lb.block,cc.description
ORDER BY 3 DESC

 * postgresql://spnf4:***@pgsql.dsa.lan/dsa_student
5 rows affected.

[('008XX N MICHIGAN AVE', 'RETAIL THEFT', 412),
 ('0000X N STATE ST', 'RETAIL THEFT', 355),
 ('076XX S CICERO AVE', 'RETAIL THEFT', 344),
 ('008XX N STATE ST', 'THEFT OF LABOR/SERVICES', 314),
 ('040XX W LAKE ST', 'THEFT OF LABOR/SERVICES', 312)]

what are the most popular three two crimes in the community areas. Most of the queries are considered as SIMPLE/CANNABIS/BATTERY crimes. People should be cautious about cars and drugs and the dealers around that area. People should aleways lock and set alarms in their cars.

In [179]:
%%sql

SELECT tbl.community_area,tbl.description, tbl.count, rank FROM 
(
SELECT la.community_area,cc.description, COUNT(*) AS count, RANK() OVER(PARTITION by la.community_area ORDER BY COUNT(*) DESC) FROM crime_code cc
JOIN crime_record cr ON cr.iucr = cc.iucr AND cr.fbi_code = cc.fbi_code
JOIN crime_location cl ON cl.cl_id = cr.cl_id
JOIN location_area la ON la.la_id = cl.lb_id
GROUP BY la.community_area,cc.description
ORDER BY 3 DESC
) AS tbl
WHERE rank<=2
ORDER BY 1,4

 * postgresql://spnf4:***@pgsql.dsa.lan/dsa_student
176 rows affected.

[(0, 'SIMPLE', 38, 1),
 (0, '$500 AND UNDER', 31, 2),
 (1, 'SIMPLE', 13, 1),
 (1, 'POSS: CANNABIS 30GMS OR LESS', 9, 2),
 (1, 'DOMESTIC BATTERY SIMPLE', 9, 2),
 (1, 'TO VEHICLE', 9, 2),
 (2, 'SIMPLE', 28, 1),
 (2, 'RETAIL THEFT', 20, 2),
 (3, 'SIMPLE', 76, 1),
 (3, 'DOMESTIC BATTERY SIMPLE', 49, 2),
 (4, 'SIMPLE', 37, 1),
 (4, 'DOMESTIC BATTERY SIMPLE', 27, 2),
 (5, 'SIMPLE', 78, 1),
 (5, 'RETAIL THEFT', 54, 2),
 (6, 'THEFT OF LABOR/SERVICES', 324, 1),
 (6, 'SIMPLE', 120, 2),
 (7, '$500 AND UNDER', 63, 1),
 (7, 'POSS: CANNABIS 30GMS OR LESS', 58, 2),
 (8, 'SIMPLE', 52, 1),
 (8, 'DOMESTIC BATTERY SIMPLE', 51, 2),
 (9, 'OVER $500', 2, 1),
 (9, 'SIMPLE', 2, 1),
 (9, 'DOMESTIC BATTERY SIMPLE', 2, 1),
 (9, 'TELEPHONE THREAT', 2, 1),
 (9, 'FINANCIAL ID THEFT: OVER $300', 2, 1),
 (10, 'SIMPLE', 23, 1),
 (10, 'DOMESTIC BATTERY SIMPLE', 22, 2),
 (11, 'DOMESTIC BATTERY SIMPLE', 20, 1),
 (11, 'POSS: CANNABIS 30GMS OR LESS', 20, 1),
 (12, 'POSS: CANNABIS 30GMS OR LESS', 18, 1),
 (12, 'SIMPLE', 15, 2),
 (13, 'SIMPLE', 15, 1),
 (13, '$500 AND UNDER', 12, 2),
 (14, 'SIMPLE', 20, 1),
 (14, 'DOMESTIC BATTERY SIMPLE', 15, 2),
 (15, 'POSS: CANNABIS 30GMS OR LESS', 67, 1),
 (15, 'SIMPLE', 56, 2),
 (16, 'RETAIL THEFT', 415, 1),
 (16, 'SIMPLE', 77, 2),
 (17, 'POSS: CANNABIS 30GMS OR LESS', 44, 1),
 (17, '$500 AND UNDER', 42, 2),
 (17, 'SIMPLE', 42, 2),
 (18, 'POSS: CRACK', 24, 1),
 (18, 'DOMESTIC BATTERY SIMPLE', 12, 2),
 (19, 'DOMESTIC BATTERY SIMPLE', 39, 1),
 (19, 'SIMPLE', 29, 2),
 (20, 'SIMPLE', 41, 1),
 (20, 'POSS: CANNABIS 30GMS OR LESS', 30, 2),
 (21, 'SIMPLE', 39, 1),
 (21, '$500 AND UNDER', 39, 1),
 (22, 'SIMPLE', 104, 1),
 (22, '$500 AND UNDER', 76, 2),
 (23, 'DOMESTIC BATTERY SIMPLE', 64, 1),
 (23, 'SIMPLE', 62, 2),
 (24, '$500 AND UNDER', 147, 1),
 (24, 'SIMPLE', 124, 2),
 (25, 'SIMPLE', 149, 1),
 (25, '$500 AND UNDER', 91, 2),
 (26, 'DOMESTIC BATTERY SIMPLE', 31, 1),
 (26, 'SIMPLE', 23, 2),
 (26, '$500 AND UNDER', 23, 2),
 (27, 'POSS: CANNABIS 30GMS OR LESS', 55, 1),
 (27, 'DOMESTIC BATTERY SIMPLE', 36, 2),
 (28, 'POSS: CANNABIS 30GMS OR LESS', 169, 1),
 (28, 'SIMPLE', 112, 2),
 (29, 'DOMESTIC BATTERY SIMPLE', 55, 1),
 (29, 'SIMPLE', 50, 2),
 (30, 'SIMPLE', 35, 1),
 (30, 'FORCIBLE ENTRY', 30, 2),
 (31, 'RETAIL THEFT', 87, 1),
 (31, 'SIMPLE', 53, 2),
 (32, 'SIMPLE', 45, 1),
 (32, 'POSS: CANNABIS 30GMS OR LESS', 36, 2),
 (33, 'SIMPLE', 38, 1),
 (33, 'DOMESTIC BATTERY SIMPLE', 31, 2),
 (34, 'DOMESTIC BATTERY SIMPLE', 45, 1),
 (34, '$500 AND UNDER', 33, 2),
 (34, 'SIMPLE', 33, 2),
 (35, 'SIMPLE', 69, 1),
 (35, 'DOMESTIC BATTERY SIMPLE', 50, 2),
 (36, 'SIMPLE', 20, 1),
 (36, '$500 AND UNDER', 12, 2),
 (36, 'TO VEHICLE', 12, 2),
 (36, 'DOMESTIC BATTERY SIMPLE', 12, 2),
 (37, 'RETAIL THEFT', 80, 1),
 (37, '$500 AND UNDER', 34, 2),
 (38, 'RETAIL THEFT', 385, 1),
 (38, 'SIMPLE', 88, 2),
 (39, 'DOMESTIC BATTERY SIMPLE', 17, 1),
 (39, 'POSS: CANNABIS 30GMS OR LESS', 16, 2),
 (40, 'SIMPLE', 19, 1),
 (40, 'DOMESTIC BATTERY SIMPLE', 16, 2),
 (41, 'DOMESTIC BATTERY SIMPLE', 27, 1),
 (41, '$500 AND UNDER', 17, 2),
 (42, '$500 AND UNDER', 39, 1),
 (42, 'OVER $500', 31, 2),
 (43, 'THEFT OF LABOR/SERVICES', 68, 1),
 (43, '$500 AND UNDER', 56, 2),
 (43, 'POSS: CANNABIS 30GMS OR LESS', 56, 2),
 (44, 'SIMPLE', 81, 1),
 (44, '$500 AND UNDER', 73, 2),
 (45, 'SIMPLE', 39, 1),
 (45, 'RETAIL THEFT', 33, 2),
 (46, 'SIMPLE', 23, 1),
 (46, '$500 AND UNDER', 16, 2),
 (47, 'RETAIL THEFT', 66, 1),
 (47, 'OVER $500', 33, 2),
 (48, 'DOMESTIC BATTERY SIMPLE', 22, 1),
 (48, 'TO PROPERTY', 16, 2),
 (49, 'SIMPLE', 42, 1),
 (49, 'DOMESTIC BATTERY SIMPLE', 39, 2),
 (50, 'TO PROPERTY', 9, 1),
 (50, 'FORCIBLE ENTRY', 8, 2),
 (50, 'SIMPLE', 8, 2),
 (51, '$500 AND UNDER', 33, 1),
 (51, 'SIMPLE', 25, 2),
 (52, 'DOMESTIC BATTERY SIMPLE', 1, 1),
 (52, 'FINANCIAL ID THEFT: OVER $300', 1, 1),
 (52, 'OVER $500', 1, 1),
 (52, 'TO VEHICLE', 1, 1),
 (52, 'TO PROPERTY', 1, 1),
 (52, '$500 AND UNDER', 1, 1),
 (52, 'CREDIT CARD FRAUD', 1, 1),
 (52, 'AUTOMOBILE', 1, 1),
 (53, 'SIMPLE', 11, 1),
 (53, 'TO VEHICLE', 8, 2),
 (53, '$500 AND UNDER', 8, 2),
 (54, 'DOMESTIC BATTERY SIMPLE', 14, 1),
 (54, 'RETAIL THEFT', 13, 2),
 (55, 'DOMESTIC BATTERY SIMPLE', 13, 1),
 (55, 'SIMPLE', 12, 2),
 (56, 'POSS: CANNABIS 30GMS OR LESS', 29, 1),
 (56, '$500 AND UNDER', 20, 2),
 (57, 'POSS: HEROIN(WHITE)', 29, 1),
 (57, 'DOMESTIC BATTERY SIMPLE', 17, 2),
 (58, 'DOMESTIC BATTERY SIMPLE', 30, 1),
 (58, '$500 AND UNDER', 21, 2),
 (59, '$500 AND UNDER', 24, 1),
 (59, 'SIMPLE', 18, 2),
 (60, 'RETAIL THEFT', 43, 1),
 (60, 'SIMPLE', 40, 2),
 (61, 'SIMPLE', 95, 1),
 (61, 'DOMESTIC BATTERY SIMPLE', 76, 2),
 (62, '$500 AND UNDER', 52, 1),
 (62, 'OVER $500', 31, 2),
 (63, 'DOMESTIC BATTERY SIMPLE', 32, 1),
 (63, 'SIMPLE', 31, 2),
 (64, 'SIMPLE', 21, 1),
 (64, 'DOMESTIC BATTERY SIMPLE', 16, 2),
 (65, 'SIMPLE', 47, 1),
 (65, 'POSS: CANNABIS 30GMS OR LESS', 22, 2),
 (66, 'SIMPLE', 81, 1),
 (66, 'DOMESTIC BATTERY SIMPLE', 43, 2),
 (67, 'SIMPLE', 39, 1),
 (67, 'DOMESTIC BATTERY SIMPLE', 39, 1),
 (68, 'SIMPLE', 118, 1),
 (68, 'DOMESTIC BATTERY SIMPLE', 97, 2),
 (69, 'SIMPLE', 71, 1),
 (69, '$500 AND UNDER', 63, 2),
 (70, 'SIMPLE', 42, 1),
 (70, '$500 AND UNDER', 18, 2),
 (71, 'SIMPLE', 72, 1),
 (71, '$500 AND UNDER', 47, 2),
 (72, 'THEFT OF LABOR/SERVICES', 46, 1),
 (72, 'POSS: CANNABIS 30GMS OR LESS', 24, 2),
 (73, 'DOMESTIC BATTERY SIMPLE', 21, 1),
 (73, 'SIMPLE', 15, 2),
 (74, 'OVER $500', 3, 1),
 (74, 'FROM BUILDING', 2, 2),
 (74, 'OTHER OFFENSE', 2, 2),
 (75, 'DOMESTIC BATTERY SIMPLE', 13, 1),
 (75, 'SIMPLE', 11, 2),
 (76, 'RETAIL THEFT', 98, 1),
 (76, 'SIMPLE', 38, 2),
 (77, 'SIMPLE', 17, 1),
 (77, 'DOMESTIC BATTERY SIMPLE', 15, 2)]

# Listing all offenses invlolving case numbers  involving child abduction. Parents should be more careful about the children in the Chicago area.

In [186]:
%%sql
SELECT primary_type,case_number,description
FROM crime_code JOIN crime_record USING(iucr)
WHERE primary_type='OFFENSE INVOLVING CHILDREN' AND description LIKE '%CHILD ABDUCTION%'

 * postgresql://spnf4:***@pgsql.dsa.lan/dsa_student
113 rows affected.

[('OFFENSE INVOLVING CHILDREN', 'HV118728', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV362932', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV464687', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV440782', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV297437', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV570526', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV363167', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV163636', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV436138', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV503836', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV509789', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV431840', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV366938', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV253941', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV618019', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV291962', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV290466', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV576707', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV231032', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV619616', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HW070028', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV308888', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV479017', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV352726', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV267597', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV482062', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV216686', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV416600', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV460904', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV548810', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV423626', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV442620', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV457074', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV334389', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV465759', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV149661', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV136235', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV429855', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV398649', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV589275', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV543653', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV276916', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV133401', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV226441', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HW199727', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV557681', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV142965', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV108459', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV449363', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV298762', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV282980', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV160380', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV537357', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV533946', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV471217', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV470437', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HW142211', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV256493', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV542950', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV162155', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV370867', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV131966', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV394185', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV214517', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV169497', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV213331', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV568512', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV564814', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV401711', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV162202', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV574639', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HW110843', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV373687', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV296125', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV262216', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV188226', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV193622', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV163683', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV341272', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV513728', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV219669', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV429341', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV486867', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV336881', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV492575', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV339866', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV208220', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV298799', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HW101252', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV412484', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV586484', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV417984', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV461858', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV614703', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV595842', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV619568', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV478835', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV184463', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV562419', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HW106658', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV267181', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV313361', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV429359', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV111278', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV568106', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV224018', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV482552', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV243811', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV438538', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV232535', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV503855', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV299338', 'CHILD ABDUCTION'),
 ('OFFENSE INVOLVING CHILDREN', 'HV316352', 'CHILD ABDUCTION')]

Unique type of crimes which have been recorded at residence location

In [185]:
%%sql
SELECT DISTINCT primary_type,location_description,iucr
FROM crime_code JOIN crime_record USING(iucr) JOIN
crime_location USING(cl_id) JOIN
location_description USING(ld_id)
WHERE location_description='RESIDENCE';

 * postgresql://spnf4:***@pgsql.dsa.lan/dsa_student
233 rows affected.

[('ASSAULT', 'RESIDENCE', '553'),
 ('THEFT', 'RESIDENCE', '860'),
 ('NARCOTICS', 'RESIDENCE', '2014'),
 ('BATTERY', 'RESIDENCE', '440'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1110'),
 ('NARCOTICS', 'RESIDENCE', '2031'),
 ('CRIMINAL DAMAGE', 'RESIDENCE', '1320'),
 ('CRIM SEXUAL ASSAULT', 'RESIDENCE', '266'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1780'),
 ('CRIM SEXUAL ASSAULT', 'RESIDENCE', '274'),
 ('ROBBERY', 'RESIDENCE', '313'),
 ('BATTERY', 'RESIDENCE', '479'),
 ('BATTERY', 'RESIDENCE', '041A'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1122'),
 ('LIQUOR LAW VIOLATION', 'RESIDENCE', '2210'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1200'),
 ('BATTERY', 'RESIDENCE', '430'),
 ('OBSCENITY', 'RESIDENCE', '1541'),
 ('PUBLIC PEACE VIOLATION', 'RESIDENCE', '2860'),
 ('MOTOR VEHICLE THEFT', 'RESIDENCE', '928'),
 ('OTHER OFFENSE', 'RESIDENCE', '2820'),
 ('OTHER OFFENSE', 'RESIDENCE', '4651'),
 ('NARCOTICS', 'RESIDENCE', '2012'),
 ('ASSAULT', 'RESIDENCE', '557'),
 ('THEFT', 'RESIDENCE', '840'),
 ('OTHER OFFENSE', 'RESIDENCE', '5110'),
 ('CRIM SEXUAL ASSAULT', 'RESIDENCE', '265'),
 ('ASSAULT', 'RESIDENCE', '530'),
 ('OTHER OFFENSE', 'RESIDENCE', '5007'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1195'),
 ('CRIMINAL TRESPASS', 'RESIDENCE', '1350'),
 ('PUBLIC PEACE VIOLATION', 'RESIDENCE', '2890'),
 ('NARCOTICS', 'RESIDENCE', '1811'),
 ('CRIM SEXUAL ASSAULT', 'RESIDENCE', '263'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1750'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1261'),
 ('ASSAULT', 'RESIDENCE', '554'),
 ('BATTERY', 'RESIDENCE', '498'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1725'),
 ('OBSCENITY', 'RESIDENCE', '1540'),
 ('CRIMINAL TRESPASS', 'RESIDENCE', '1365'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '1477'),
 ('THEFT', 'RESIDENCE', '843'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1156'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1751'),
 ('CRIMINAL TRESPASS', 'RESIDENCE', '1360'),
 ('CRIM SEXUAL ASSAULT', 'RESIDENCE', '261'),
 ('STALKING', 'RESIDENCE', '581'),
 ('OTHER OFFENSE', 'RESIDENCE', '501A'),
 ('THEFT', 'RESIDENCE', '810'),
 ('BATTERY', 'RESIDENCE', '041B'),
 ('CRIM SEXUAL ASSAULT', 'RESIDENCE', '271'),
 ('NARCOTICS', 'RESIDENCE', '2021'),
 ('NARCOTICS', 'RESIDENCE', '2020'),
 ('NARCOTICS', 'RESIDENCE', '2026'),
 ('STALKING', 'RESIDENCE', '583'),
 ('THEFT', 'RESIDENCE', '820'),
 ('NARCOTICS', 'RESIDENCE', '2090'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1791'),
 ('BATTERY', 'RESIDENCE', '460'),
 ('SEX OFFENSE', 'RESIDENCE', '1565'),
 ('ROBBERY', 'RESIDENCE', '031A'),
 ('SEX OFFENSE', 'RESIDENCE', '1544'),
 ('KIDNAPPING', 'RESIDENCE', '1792'),
 ('KIDNAPPING', 'RESIDENCE', '4255'),
 ('SEX OFFENSE', 'RESIDENCE', '1570'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1245'),
 ('ASSAULT', 'RESIDENCE', '552'),
 ('THEFT', 'RESIDENCE', '890'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1582'),
 ('NARCOTICS', 'RESIDENCE', '2027'),
 ('PROSTITUTION', 'RESIDENCE', '1505'),
 ('NARCOTICS', 'RESIDENCE', '2024'),
 ('BURGLARY', 'RESIDENCE', '620'),
 ('CRIM SEXUAL ASSAULT', 'RESIDENCE', '275'),
 ('CRIM SEXUAL ASSAULT', 'RESIDENCE', '291'),
 ('NARCOTICS', 'RESIDENCE', '2017'),
 ('CRIMINAL TRESPASS', 'RESIDENCE', '1330'),
 ('CRIMINAL DAMAGE', 'RESIDENCE', '1340'),
 ('BURGLARY', 'RESIDENCE', '630'),
 ('ASSAULT', 'RESIDENCE', '051B'),
 ('NARCOTICS', 'RESIDENCE', '1822'),
 ('ASSAULT', 'RESIDENCE', '560'),
 ('NARCOTICS', 'RESIDENCE', '2029'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1155'),
 ('OTHER OFFENSE', 'RESIDENCE', '5008'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1130'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1754'),
 ('NARCOTICS', 'RESIDENCE', '2170'),
 ('NARCOTICS', 'RESIDENCE', '2040'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1210'),
 ('OTHER OFFENSE', 'RESIDENCE', '5001'),
 ('SEX OFFENSE', 'RESIDENCE', '1576'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1135'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '141A'),
 ('THEFT', 'RESIDENCE', '870'),
 ('MOTOR VEHICLE THEFT', 'RESIDENCE', '930'),
 ('CRIMINAL DAMAGE', 'RESIDENCE', '1305'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1152'),
 ('ROBBERY', 'RESIDENCE', '330'),
 ('SEX OFFENSE', 'RESIDENCE', '1566'),
 ('SEX OFFENSE', 'RESIDENCE', '5004'),
 ('SEX OFFENSE', 'RESIDENCE', '1562'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '142B'),
 ('ROBBERY', 'RESIDENCE', '340'),
 ('BATTERY', 'RESIDENCE', '486'),
 ('ROBBERY', 'RESIDENCE', '312'),
 ('NARCOTICS', 'RESIDENCE', '2028'),
 ('INTERFERENCE WITH PUBLIC OFFICER', 'RESIDENCE', '3710'),
 ('STALKING', 'RESIDENCE', '584'),
 ('BATTERY', 'RESIDENCE', '454'),
 ('BATTERY', 'RESIDENCE', '452'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '2900'),
 ('OTHER OFFENSE', 'RESIDENCE', '4650'),
 ('BATTERY', 'RESIDENCE', '475'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1185'),
 ('ARSON', 'RESIDENCE', '1020'),
 ('PROSTITUTION', 'RESIDENCE', '1525'),
 ('MOTOR VEHICLE THEFT', 'RESIDENCE', '920'),
 ('CRIM SEXUAL ASSAULT', 'RESIDENCE', '264'),
 ('OTHER OFFENSE', 'RESIDENCE', '5003'),
 ('ARSON', 'RESIDENCE', '1090'),
 ('LIQUOR LAW VIOLATION', 'RESIDENCE', '2230'),
 ('BATTERY', 'RESIDENCE', '488'),
 ('SEX OFFENSE', 'RESIDENCE', '1585'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1753'),
 ('MOTOR VEHICLE THEFT', 'RESIDENCE', '917'),
 ('NARCOTICS', 'RESIDENCE', '2025'),
 ('INTIMIDATION', 'RESIDENCE', '3960'),
 ('NARCOTICS', 'RESIDENCE', '2022'),
 ('NARCOTICS', 'RESIDENCE', '2023'),
 ('OTHER OFFENSE', 'RESIDENCE', '4310'),
 ('OTHER OFFENSE', 'RESIDENCE', '5011'),
 ('THEFT', 'RESIDENCE', '865'),
 ('INTERFERENCE WITH PUBLIC OFFICER', 'RESIDENCE', '3760'),
 ('INTERFERENCE WITH PUBLIC OFFICER', 'RESIDENCE', '3730'),
 ('BURGLARY', 'RESIDENCE', '610'),
 ('OTHER OFFENSE', 'RESIDENCE', '5000'),
 ('OTHER OFFENSE', 'RESIDENCE', '2825'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1720'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1710'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1205'),
 ('NARCOTICS', 'RESIDENCE', '1812'),
 ('OTHER OFFENSE', 'RESIDENCE', '500N'),
 ('ROBBERY', 'RESIDENCE', '320'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1220'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '1460'),
 ('ASSAULT', 'RESIDENCE', '550'),
 ('SEX OFFENSE', 'RESIDENCE', '1563'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '143A'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1537'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1150'),
 ('OTHER OFFENSE', 'RESIDENCE', '2826'),
 ('BATTERY', 'RESIDENCE', '496'),
 ('BURGLARY', 'RESIDENCE', '650'),
 ('BATTERY', 'RESIDENCE', '497'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1120'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '143B'),
 ('OTHER OFFENSE', 'RESIDENCE', '4387'),
 ('STALKING', 'RESIDENCE', '580'),
 ('ROBBERY', 'RESIDENCE', '334'),
 ('KIDNAPPING', 'RESIDENCE', '4220'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1242'),
 ('MOTOR VEHICLE THEFT', 'RESIDENCE', '915'),
 ('THEFT', 'RESIDENCE', '841'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1140'),
 ('ASSAULT', 'RESIDENCE', '520'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1121'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '141B'),
 ('NARCOTICS', 'RESIDENCE', '2093'),
 ('OTHER OFFENSE', 'RESIDENCE', '5002'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '141C'),
 ('OTHER OFFENSE', 'RESIDENCE', '4810'),
 ('NARCOTICS', 'RESIDENCE', '2091'),
 ('MOTOR VEHICLE THEFT', 'RESIDENCE', '925'),
 ('CRIM SEXUAL ASSAULT', 'RESIDENCE', '281'),
 ('GAMBLING', 'RESIDENCE', '1661'),
 ('ARSON', 'RESIDENCE', '1025'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1170'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1790'),
 ('THEFT', 'RESIDENCE', '842'),
 ('BATTERY', 'RESIDENCE', '420'),
 ('NARCOTICS', 'RESIDENCE', '2013'),
 ('BATTERY', 'RESIDENCE', '495'),
 ('ASSAULT', 'RESIDENCE', '051A'),
 ('SEX OFFENSE', 'RESIDENCE', '1564'),
 ('PUBLIC PEACE VIOLATION', 'RESIDENCE', '2850'),
 ('PUBLIC PEACE VIOLATION', 'RESIDENCE', '3000'),
 ('OTHER OFFENSE', 'RESIDENCE', '2830'),
 ('NARCOTICS', 'RESIDENCE', '1821'),
 ('MOTOR VEHICLE THEFT', 'RESIDENCE', '910'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1153'),
 ('CRIMINAL DAMAGE', 'RESIDENCE', '1345'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '143C'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1151'),
 ('NARCOTICS', 'RESIDENCE', '2016'),
 ('INTERFERENCE WITH PUBLIC OFFICER', 'RESIDENCE', '3800'),
 ('KIDNAPPING', 'RESIDENCE', '4230'),
 ('THEFT', 'RESIDENCE', '850'),
 ('THEFT', 'RESIDENCE', '880'),
 ('CRIMINAL DAMAGE', 'RESIDENCE', '1310'),
 ('NARCOTICS', 'RESIDENCE', '1850'),
 ('OTHER OFFENSE', 'RESIDENCE', '4388'),
 ('KIDNAPPING', 'RESIDENCE', '4210'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1154'),
 ('BATTERY', 'RESIDENCE', '485'),
 ('BATTERY', 'RESIDENCE', '482'),
 ('NARCOTICS', 'RESIDENCE', '2018'),
 ('OTHER OFFENSE', 'RESIDENCE', '4510'),
 ('WEAPONS VIOLATION', 'RESIDENCE', '142A'),
 ('NARCOTICS', 'RESIDENCE', '2015'),
 ('INTIMIDATION', 'RESIDENCE', '3970'),
 ('PROSTITUTION', 'RESIDENCE', '1531'),
 ('NARCOTICS', 'RESIDENCE', '2092'),
 ('PUBLIC PEACE VIOLATION', 'RESIDENCE', '2870'),
 ('OTHER OFFENSE', 'RESIDENCE', '4800'),
 ('ROBBERY', 'RESIDENCE', '337'),
 ('OTHER OFFENSE', 'RESIDENCE', '4625'),
 ('PUBLIC PEACE VIOLATION', 'RESIDENCE', '470'),
 ('SEX OFFENSE', 'RESIDENCE', '1590'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1752'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1206'),
 ('NARCOTICS', 'RESIDENCE', '2094'),
 ('BATTERY', 'RESIDENCE', '484'),
 ('OTHER OFFENSE', 'RESIDENCE', '500E'),
 ('ASSAULT', 'RESIDENCE', '545'),
 ('SEX OFFENSE', 'RESIDENCE', '1580'),
 ('LIQUOR LAW VIOLATION', 'RESIDENCE', '2220'),
 ('INTERFERENCE WITH PUBLIC OFFICER', 'RESIDENCE', '3731'),
 ('PUBLIC PEACE VIOLATION', 'RESIDENCE', '2851'),
 ('OFFENSE INVOLVING CHILDREN', 'RESIDENCE', '1755'),
 ('ROBBERY', 'RESIDENCE', '033A'),
 ('DECEPTIVE PRACTICE', 'RESIDENCE', '1240')]

## End of the Project

# Save your notebook, then `File > Close and Halt`